spring:
  application:
    name: identity-service

  data:
    mongodb:
      uri: ${DB_CONNECTION_STRING}
      uuid-representation: standard

jwt:
  public:
    key: classpath:app.pub

server:
  port:
    8081
