spring:
  application:
    name: item-service

  data:
    mongodb:
      uri: ${DB_CONNECTION_STRING}
      uuid-representation: standard
jwt:
  public:
    key: classpath:app.pub

gateway:
  host: ${GATEWAY_HOST}
  restaurant:
    route: ${GATEWAY_RESTAURANT_ROUTE}

server:
  port:
    8084
